# Generated by Django 4.0.5 on 2022-06-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcate', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default=None, max_length=100)),
                ('date_inscripion', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcommande', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.client')),
            ],
        ),
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproduit', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('photos', models.CharField(max_length=100)),
                ('marques', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.categories')),
            ],
        ),
        migrations.CreateModel(
            name='listeproduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=100)),
                ('commandes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.commandes')),
                ('produits', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.produits')),
            ],
        ),
    ]
